const STREAM='https://live.ontodaytv.com/hls/ontoday.m3u8';
const POSTS='https://ontodaytv.com/wp-json/wp/v2/posts?per_page=12&_embed';
const translations={
 en:{home:'Home',watch:'Watch',programs:'Programs',businessNav:'Business',more:'More',liveNow:'LIVE NOW',heroTitle:'Today TV — Live from Los Angeles',heroCopy:'Persian-American television, interviews, culture and community—available wherever you are.',watchLive:'Watch Live',listenRadio:'Listen to Radio',onAir:'ON AIR',tapWatch:'Tap to watch live',latest:'LATEST',featured:'Featured Programs',viewAll:'View all',network:'THE NETWORK',connectTitle:'Watch. Listen. Connect.',liveTv:'Live TV',liveTvCopy:'Watch the broadcast',radio:'Radio Today',radioCopy:'Listen from Los Angeles',advertise:'Advertise',advertiseCopy:'Reach our community',business:'BUSINESS',reach:'Reach Persian-American audiences',reachCopy:'Advertising, sponsored interviews, business listings and creative production.',advertiseUs:'Advertise with us',listBusiness:'List your business',liveBroadcast:'LIVE BROADCAST',watchTitle:'Watch Today TV Live',startStream:'Start live stream',ready:'Ready',connecting:'Connecting',live:'Live',offline:'Offline',share:'Share',websitePlayer:'Website player',streamError:'The live stream could not connect.',retry:'Retry',qualityNote:'Playback quality depends on your internet connection. The stream does not start until you press play.',discover:'DISCOVER',programsTitle:'Programs & Stories',search:'Search programs',all:'All',interviews:'Interviews',culture:'Culture',businessTitle:'Business',entertainment:'Entertainment',postsUnavailable:'Programs are temporarily unavailable here.',visitSite:'Visit TodayTV.com',partner:'PARTNER WITH US',businessHero:'Grow your brand with Persian-American media.',businessCopy:'Choose the fastest path to visibility. Every inquiry continues securely on TodayTV.com.',preferEmail:'PREFER EMAIL?',emailUs:'Email Today TV',about:'ABOUT',storyTitle:'Persian-American media since 1982',story:'Founded by filmmaker and executive producer Farzan Deljou, Today TV connects Persian-speaking audiences through television, interviews, culture and digital storytelling.',install:'Install Today TV',installCopy:'Add the app to your home screen',iosInstall:'On iPhone: tap Share, then Add to Home Screen.',copied:'Link copied',readMore:'Read story',noResults:'No programs match your search.'},
 fa:{home:'خانه',watch:'پخش زنده',programs:'برنامه‌ها',businessNav:'تبلیغات',more:'بیشتر',liveNow:'پخش زنده',heroTitle:'تلویزیون امروز — پخش زنده از لس‌آنجلس',heroCopy:'تلویزیون ایرانی-آمریکایی، مصاحبه‌ها، فرهنگ و جامعه — هر کجا که هستید.',watchLive:'تماشای زنده',listenRadio:'شنیدن رادیو',onAir:'روی آنتن',tapWatch:'برای تماشای زنده بزنید',latest:'تازه‌ترین',featured:'برنامه‌های ویژه',viewAll:'مشاهده همه',network:'شبکه امروز',connectTitle:'تماشا کنید. بشنوید. همراه شوید.',liveTv:'تلویزیون زنده',liveTvCopy:'پخش مستقیم را تماشا کنید',radio:'رادیو امروز',radioCopy:'پخش از لس‌آنجلس',advertise:'تبلیغات',advertiseCopy:'با جامعه ما ارتباط بگیرید',business:'کسب‌وکار',reach:'دسترسی به مخاطبان ایرانی-آمریکایی',reachCopy:'تبلیغات، مصاحبه‌های حمایتی، فهرست کسب‌وکارها و تولید خلاق.',advertiseUs:'تبلیغات با ما',listBusiness:'ثبت کسب‌وکار',liveBroadcast:'پخش زنده',watchTitle:'تماشای زنده تلویزیون امروز',startStream:'شروع پخش زنده',ready:'آماده',connecting:'در حال اتصال',live:'زنده',offline:'آفلاین',share:'اشتراک‌گذاری',websitePlayer:'پخش در وب‌سایت',streamError:'اتصال به پخش زنده ممکن نشد.',retry:'تلاش دوباره',qualityNote:'کیفیت پخش به اینترنت شما بستگی دارد. پخش تا زمانی که دکمه را نزنید شروع نمی‌شود.',discover:'کشف کنید',programsTitle:'برنامه‌ها و داستان‌ها',search:'جستجوی برنامه‌ها',all:'همه',interviews:'مصاحبه‌ها',culture:'فرهنگ',businessTitle:'کسب‌وکار',entertainment:'سرگرمی',postsUnavailable:'برنامه‌ها موقتاً در اینجا در دسترس نیستند.',visitSite:'بازدید از TodayTV.com',partner:'همکاری با ما',businessHero:'برند خود را با رسانه ایرانی-آمریکایی رشد دهید.',businessCopy:'سریع‌ترین مسیر برای دیده‌شدن را انتخاب کنید. درخواست شما در TodayTV.com ادامه می‌یابد.',preferEmail:'ترجیح می‌دهید ایمیل بزنید؟',emailUs:'ایمیل به تلویزیون امروز',about:'درباره ما',storyTitle:'رسانه ایرانی-آمریکایی از سال ۱۹۸۲',story:'تلویزیون امروز به بنیان‌گذاری فرزان دلجو، فیلمساز و تهیه‌کننده اجرایی، مخاطبان فارسی‌زبان را از طریق تلویزیون، مصاحبه، فرهنگ و داستان‌گویی دیجیتال به هم پیوند می‌دهد.',install:'نصب تلویزیون امروز',installCopy:'اپ را به صفحه اصلی اضافه کنید',iosInstall:'در آیفون: Share و سپس Add to Home Screen را بزنید.',copied:'لینک کپی شد',readMore:'ادامه مطلب',noResults:'برنامه‌ای با جستجوی شما پیدا نشد.'}
};
const navItems=[['home','⌂','home'],['watch','▶','watch'],['programs','▦','programs'],['businessNav','↗','business'],['more','•••','more']];
let lang=localStorage.getItem('todaytv-lang')||'en',posts=[],activeFilter='all',hls,deferredInstall;
const t=k=>translations[lang][k]||translations.en[k]||k;
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const stripHtml=s=>{const d=document.createElement('div');d.innerHTML=s||'';return d.textContent||''};

function renderNav(){const html=navItems.map(([key,icon,id])=>`<button data-view="${id}" class="${currentView()===id?'active':''}"><span>${icon}</span><span>${t(key)}</span></button>`).join('');document.querySelector('.mobile-nav').innerHTML=html;document.querySelector('.desktop-nav').innerHTML=navItems.map(([key,,id])=>`<button data-view="${id}" class="${currentView()===id?'active':''}">${t(key)}</button>`).join('');}
function currentView(){const active=document.querySelector('.view.active');return active?.dataset.viewId||active?.id||'home'}
function showView(id,push=true){const target=id==='business'?document.querySelector('[data-view-id="business"]'):document.getElementById(id);if(!target)return;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));target.classList.add('active');if(push)history.pushState({view:id},'',`#${id}`);renderNav();window.scrollTo({top:0,behavior:'smooth'});document.getElementById('main').focus({preventScroll:true});}
function applyLanguage(){document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';document.getElementById('languageToggle').textContent=lang==='en'?'FA':'EN';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));renderNav();renderServices();renderMoreLinks();renderPosts();}

function postCard(p){const image=p?._embedded?.['wp:featuredmedia']?.[0]?.source_url;const title=stripHtml(p?.title?.rendered)||'Today TV';const excerpt=stripHtml(p?.excerpt?.rendered);const date=p?.date?new Intl.DateTimeFormat(lang==='fa'?'fa-IR':'en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(p.date)):'';return `<article class="program-card"><div class="program-image">${image?`<img src="${escapeHtml(image)}" alt="" loading="lazy" onerror="this.remove()">`:'<span class="fallback-mark">T</span>'}</div><div class="program-body"><time>${escapeHtml(date)}</time><h3>${escapeHtml(title)}</h3><p>${escapeHtml(excerpt)}</p><a href="${escapeHtml(p?.link||'https://ontodaytv.com/')}" target="_blank" rel="noopener">${t('readMore')} →</a></div></article>`}
function renderPosts(){const grid=document.getElementById('programGrid'),featured=document.getElementById('featuredGrid');if(!grid||!featured)return;if(!posts.length){const skeleton='<div class="program-card skeleton"></div>';grid.innerHTML=skeleton.repeat(6);featured.innerHTML=skeleton.repeat(3);return}const q=(document.getElementById('programSearch')?.value||'').toLowerCase();const filtered=posts.filter(p=>{const text=(stripHtml(p.title?.rendered)+' '+stripHtml(p.excerpt?.rendered)).toLowerCase();return text.includes(q)&&(activeFilter==='all'||text.includes(activeFilter))});grid.innerHTML=filtered.length?filtered.map(postCard).join(''):`<div class="notice"><p>${t('noResults')}</p></div>`;featured.innerHTML=posts.slice(0,3).map(postCard).join('')}
async function loadPosts(){try{const res=await fetch(POSTS,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error('Posts unavailable');posts=await res.json();if(!Array.isArray(posts)||!posts.length)throw new Error('No posts');renderPosts()}catch(e){posts=[];document.getElementById('programGrid').innerHTML='';document.getElementById('featuredGrid').innerHTML=`<div class="notice"><p>${t('postsUnavailable')}</p><a href="https://ontodaytv.com/" target="_blank" rel="noopener">${t('visitSite')} →</a></div>`;document.getElementById('programNotice').hidden=false}}

function setStatus(key,state=''){const el=document.getElementById('streamStatus');el.className=`status ${state}`;el.innerHTML=`<i></i><span>${t(key)}</span>`}
function startStream(){const video=document.getElementById('liveVideo');document.getElementById('videoOverlay').classList.add('hidden');document.getElementById('streamError').hidden=true;setStatus('connecting');if(hls){hls.destroy();hls=null}if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=STREAM;video.play().catch(()=>{})}else if(window.Hls?.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:false,liveSyncDurationCount:3,liveMaxLatencyDurationCount:5,maxBufferLength:20,backBufferLength:20});hls.loadSource(STREAM);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>video.play().catch(()=>{}));hls.on(Hls.Events.ERROR,(_,data)=>{if(data.fatal)streamFailed()})}else streamFailed()}
function streamFailed(){setStatus('offline');document.getElementById('streamError').hidden=false;document.getElementById('videoOverlay').classList.remove('hidden')}
function renderServices(){const items=[['↗',t('advertise'),'TV commercials, digital campaigns and sponsored media.','https://ontodaytv.com/advertise-with-today-tv/'],['＋',t('listBusiness'),'Join the Today TV business directory.','https://ontodaytv.com/submit-claim-your-business/'],['●',lang==='fa'?'تولید و استودیو':'Production & Studio','Podcast, livestream, filming and editing services.','https://ontodaytv.com/our-services/'],['◎',lang==='fa'?'مصاحبه حمایتی':'Sponsored Interview','Tell your story through a professionally produced feature.','https://ontodaytv.com/contact-us/']];document.getElementById('serviceGrid').innerHTML=items.map(([icon,title,copy,url])=>`<article class="service-card"><span>${icon}</span><h2>${title}</h2><p>${copy}</p><a href="${url}" target="_blank" rel="noopener">${lang==='fa'?'اطلاعات بیشتر':'Learn more'} →</a></article>`).join('')}
function renderMoreLinks(){const items=[['◉',t('radio'),'https://ontodaytv.com/radio-today-los-angeles/'],['▣','Instagram','https://www.instagram.com/ontodaytv/'],['▶','YouTube','https://www.youtube.com/'],['↗',lang==='fa'?'تماس با ما':'Contact Today TV','https://ontodaytv.com/contact-us/'],['§',lang==='fa'?'حریم خصوصی':'Privacy Policy','https://ontodaytv.com/privacy-policy/'],['§',lang==='fa'?'شرایط استفاده':'Terms','https://ontodaytv.com/terms-and-conditions/']];document.getElementById('moreLinks').innerHTML=items.map(([icon,label,url])=>`<a href="${url}" target="_blank" rel="noopener"><span>${icon}</span><b>${label}</b><span>→</span></a>`).join('')}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}

document.addEventListener('click',e=>{const control=e.target.closest('[data-view]');if(control){e.preventDefault();showView(control.dataset.view)}if(e.target.closest('#videoOverlay'))startStream()});
document.getElementById('languageToggle').addEventListener('click',()=>{lang=lang==='en'?'fa':'en';localStorage.setItem('todaytv-lang',lang);applyLanguage()});
document.getElementById('retryButton').addEventListener('click',startStream);
document.getElementById('shareButton').addEventListener('click',async()=>{const data={title:'Today TV Live',url:'https://ontodaytv.com/watch-today-tv-live/'};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);toast(t('copied'))}}catch{}});
document.getElementById('liveVideo').addEventListener('playing',()=>setStatus('live','live'));document.getElementById('liveVideo').addEventListener('waiting',()=>setStatus('connecting'));document.getElementById('liveVideo').addEventListener('error',streamFailed);
document.getElementById('programSearch').addEventListener('input',renderPosts);document.querySelector('.filters').addEventListener('click',e=>{const chip=e.target.closest('[data-filter]');if(!chip)return;document.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));chip.classList.add('active');activeFilter=chip.dataset.filter;renderPosts()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});window.addEventListener('appinstalled',()=>toast('Today TV installed'));
document.getElementById('installButton').addEventListener('click',async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else{document.getElementById('iosInstall').hidden=false;document.getElementById('iosInstall').scrollIntoView({behavior:'smooth',block:'center'})}});
window.addEventListener('popstate',()=>showView((location.hash||'#home').slice(1),false));
window.addEventListener('online',()=>toast(lang==='fa'?'دوباره آنلاین شدید':'Back online'));window.addEventListener('offline',()=>toast(lang==='fa'?'آفلاین هستید':'You are offline'));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
showView((location.hash||'#home').slice(1),false);applyLanguage();renderServices();renderMoreLinks();loadPosts();
